### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by jonobacon** [jonobacon/eventbrite-tools#2]
Currently we have no tests for etools. It could be helpful to have some tests to ensure we don't break anything moving forward.

**Comment by joedborg** [comment]
If you can provide a test input file, i can work on this

**Comment by jonobacon** [comment]
@joedborg when you say and "input file", I presume you mean the order input file from eventbrite?

**Comment by joedborg** [comment]
Yes mate. I think you have me email so feel free to email an example.

**Comment by jonobacon** [comment]
I created a `tests` folder and added some sample data. :-)

**Comment by joedborg** [comment]
PR 3
